# Simple workflow for deploying static content to GitHub Pages
name: Deploy to Github Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          # cache-dependency-path: "package-lock.json" # uncomment if your lockfile is not at repo root

      - name: Install dependencies
        run: npm ci
        # working-directory: ./your-app   # uncomment and set if app is in a subfolder

      - name: Build
        run: npm run build
        env:
          CI: true
        # working-directory: ./your-app   # keep in sync with step above

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./build" # change to ./your-app/build if using working-directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
